project_groups:
  - name: Prevention
    body: Inform, reduce, and control the spread of the outbreak.
    project_types:
      - Track the outbreak
      - Reduce spread
    color: orange
  - name: Medical
    body: Support our overwhelmed health systems with medical innovation.
    project_types:
      - Scale testing
      - Medical facilities
      - Medical equipments
      - Treatment R&D
    color: indigo
  - name: Community
    body: Work together to help our stressed communities.
    project_types:
      - E-Learning
      - Job placement
      - Mental health
      - Help out communities
      - Map volunteers to needs
      - News and information
      - Social giving
    color: blue

global_announcements:
  - title: Helpful resources for your projects
    sub_title: We wrote a playbook on how to manage volunteers, had some amazing panels, and gathered some deals for you.
    cta_text: Browse resources
    cta_url: /offers

events:
  - title: HWC Volunteer Playbook
    sub_title: A short guide created by our team to help you successfully manager your project and volunteers!
    cta_text: Download playbook
    cta_url: https://docs.google.com/document/d/1f_-g893NGawa5n4KyDw6zjrocO2VBS5b2siQIZ6csY0/view
  - title: A Global Perspective on Problems Needing Solutions Regarding COVID-19 Response. Live Panel with Ambika Bumb
    sub_title: Ambika is a Health, Science and Technology Advisor focusing on Crisis Management and Strategy
    cta_text: View recording
    cta_url: https://drive.google.com/a/openai.com/file/d/1I3TjGcWQUsoKGP5dbPT7WD244UjDYiXf/view?usp=drive_web
  - title: Lean thinking in a Crisis. Live Panel with Eric Ries
    sub_title: Eric is an entrepreneur and the author of the New York Times bestseller The Lean Startup. He is the creator of the Lean Startup methodology, which has become a global movement in business, practiced by individuals and companies around the world.
    cta_text: View recording
    cta_url: https://drive.google.com/a/openai.com/file/d/1r8PBT_h2ZcnyMExV_hx6B7W8-n35BpgE/view?usp=drive_web
  - title: Live panel on Philanthropic Fundraising
    sub_title: Jennifer Pisansky has 10 years of experience in philanthropic fundraising and talks about raising from foundations.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/share/3dZaM6vJy1NJfp3c2UHkfa8oQL-7T6a82yRN-fsOmkl9jfRS3GPg-L-gS4Y9zJu3
  - title: Live panel on How to Scale Volunteers
    sub_title: Glen Moriarty, founder of 7cups on how he manages 320k volunteers.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/play/vZN-dbuq-m03TNKSsASDAfEtW466J6qs1XQWrvtYxRvmU3QDNVv0NLJGYbffjdiMo1gf68qHVnbe2mOi?continueMode=true
  - title: Live panel on Picking Ideas to Work On
    sub_title: Ivan Gayton, former Head of Mission and Board Member at Doctors without Border, talks about building technology for humanitarian/emergency purposes.
    cta_text: View recording
    cta_url: https://zoom.us/rec/share/5sttA5fAsWxLT6_Nx2-Yd7IEDqfuaaa823JI8_tcyUYSZzIbgvNy717m1UGGegEf
  - title: Rethinking Resumes | Creating Impact in the age of Insta-everything
    sub_title: Monday, April 20th 1:30pm PST | <a href="https://www.linkedin.com/in/jaimiefeliz/">Jaimie Lynn Craig Feliz</a>, Founder of The Hire Standard and Bay Area search and resume guru gives actionable insights and tactics to influence, connect and ultimately be seen as the expert you are.
    cta_text: Click here to add to your calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=MzBrdnRnb2RsbDdsbWxxdWNwMTdldDliOGogb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com
  - title: Sourcing a Volunteer Workforce from TeamBlind’s 3.5MM+ Professionals with Kyum Kim
    sub_title: Tuesday, April 21st 12pm-12:30pm PST
    cta_text: Click here to add to your calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=NDlraGs0bGxiZXMzNmI0aTh2aDF0M3NrNWEgb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com

upcoming_events:
  - title: How to Sell and Know Your Audience | Live Panel with ClozeLoop Founders, Hilmon Sorey and Corey Bray
    sub_title: Monday, April 27th 11am PST | <a href="https://www.linkedin.com/in/hilmonsorey/"> Hilmon Sorey</a> and <a href="https://www.linkedin.com/in/buy-triangleselling/">Cory Bray</a>  are Managing Directors of ClozeLoop and have written 5 books on sales, sales enablement, and sales management.  Their 6th book, The Five Secrets of a Sales Coach will be released in May.
    cta_text: Click here to add to your calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=MmNrN2QwMW0zOWtuczgzZTYwc2xkbDRpZW0gb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com
  - title: Private Group Office Hours with Sam Altman
    sub_title: Friday, May 1st 12pm PST | 3 randomly selected Project Owners will have time to discuss their project’s biggest challenges and solicit feedback from Sam.
    cta_text: Fill out this form if you are interested in joining us
    cta_url: https://forms.gle/jNFYAd1oLtQjLJrP9
