# Main
site_title: Help With Black Equity
site_subtitle: Projects to advance equity for the Black community
site_url: https://helpwithblackequity.herokuapp.com
share_image: https://helpwithblackequity.herokuapp.com/share-image.png

# Site features
features_enabled:
  volunteer_directory: true
  resources: true
  office_hours: true
  success_stories: true

project_categories:
  - name: Education
    slug: education
    body: Closing the gap in our education system
    project_types:
      - Scale testing
      - Medical facilities
      - Medical equipments
      - Treatment R&D
    color: cat-education
  - name: Social Justice
    slug: social-justice
    body: Directly impact social inequalities
    project_types:
      - Track the outbreak
      - Reduce spread
    color: cat-social-justice
  - name: Business Directory
    slug: business-directory
    body: Support black owned businesses
    project_types:
      - E-Learning
      - Job placement
      - Mental health
      - Help out communities
      - Map volunteers to needs
      - News and information
      - Social giving
    color: cat-business-directory
  - name: Health
    slug: health
    body: Prevention, wellness and cures
    project_types:
      - E-Learning
      - Job placement
      - Mental health
      - Help out communities
      - Map volunteers to needs
      - News and information
      - Social giving
    color: cat-health
  - name: Wealth
    slug: wealth
    body: Employment, funding and ownership
    project_types:
      - E-Learning
      - Job placement
      - Mental health
      - Help out communities
      - Map volunteers to needs
      - News and information
      - Social giving
    color: cat-wealth

google_fonts_request: 'Lora&family=Roboto:wght@400;500;700'

homepage_featured_projects_count: 12
